services:
  - type: web
    name: fastapi-inventory
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

databases:
  - name: inventory-db
